version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boxen
    versions:
    - 5.0.0
  - dependency-name: chalk
    versions:
    - 4.1.0
